from __future__ import annotations

import os
import re
import string
import unicodedata
from pathlib import Path

import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from forge.src.brand_profile import BrandProfile


_ABSOLUTE_BANS = [
    "elevate",
    "empower",
    "seamless",
    "leverage",
    "innovative",
    "cutting-edge",
    "transform",
    "unlock",
]

_CONTENT_TYPE_INSTRUCTIONS = {
    "instagram_caption": "Write a punchy Instagram caption that grabs attention in the first line, uses the brand voice, and ends with a soft CTA.",
    "email_subject": "Write a concise email subject line under 60 characters that creates curiosity and sounds like the brand.",
    "blog_intro": "Write an engaging blog introduction paragraph that sets up a clear promise and pulls the reader in with the brand's tone.",
    "tweet": "Write a sharp, memorable tweet under 280 characters that sounds like it came from the brand, not a marketing team.",
    "linkedin_post": "Write a professional but human LinkedIn post that shares insight or perspective in the brand's voice.",
}


_SKILL_CODE_TEMPLATE = string.Template('''\
"""$brand_name content generator. Auto-generated by Brand Studio Forge."""

BRAND = {
    "name": $brand_name_repr,
    "voice": $voice_repr,
    "primary_color": $primary_repr,
    "secondary_color": $secondary_repr,
    "display_font": $display_repr,
    "body_font": $body_repr,
    "tagline": $tagline_repr,
    "tone_rules": $tone_rules_repr,
    "content_types": $content_types_repr,
    "banned_words": $banned_words_repr,
}


def generate_content(content_type="instagram_caption", topic="brand update", model="hermes-4"):
    """Construct a prompt baking in BRAND voice rules, tone_rules, and banned_words."""
    brand = BRAND
    instruction = brand["content_types"].get(
        content_type,
        brand["content_types"].get("instagram_caption", "Write brand-voice content."),
    )
    rules_block = "\\n".join(f"- {r}" for r in brand["tone_rules"])
    bans_block = "\\n".join(f"- {w}" for w in brand["banned_words"])

    prompt = (
        f"You are the voice of {brand['name']}. "
        f"Voice: {brand['voice']}\\n\\n"
        f"Tone rules:\\n{rules_block}\\n\\n"
        f"Banned words — NEVER use these:\\n{bans_block}\\n\\n"
        f"Task: {instruction}\\n\\n"
        f"Topic: {topic}\\n\\n"
        f"Generate brand-voice content for: {topic}"
    )
    return prompt


def generate_weekly_calendar():
    """Return a 7-day content calendar derived from brand identity."""
    brand = BRAND
    return {
        "monday":    {"type": "linkedin_post",       "topic": f"{brand['name']} industry insight"},
        "tuesday":   {"type": "instagram_caption",   "topic": f"Behind the scenes at {brand['name']}"},
        "wednesday": {"type": "tweet",               "topic": f"A quick thought from {brand['name']}"},
        "thursday":  {"type": "blog_intro",          "topic": f"{brand['name']} how-to or deep dive"},
        "friday":    {"type": "email_subject",       "topic": f"Weekend edition from {brand['name']}"},
        "saturday":  {"type": "instagram_caption",   "topic": f"Weekend vibe with {brand['name']}"},
        "sunday":    {"type": "linkedin_post",       "topic": f"Reflection: {brand['name']} weekly roundup"},
    }


def get_brand_info():
    """Return the BRAND dict for Hermes introspection."""
    return BRAND
''')


def _to_slug(name: str) -> str:
    normalized = name.lower().strip()
    normalized = unicodedata.normalize("NFKD", normalized)
    normalized = "".join(c for c in normalized if not unicodedata.combining(c))
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    normalized = re.sub(r"_+", "_", normalized)
    return normalized.strip("_")


def _render_code(profile: BrandProfile) -> str:
    slug = _to_slug(profile.name)
    brand_name = profile.name
    voice = profile.voice_tone or "professional and clear"
    primary = profile.primary_color or "#000000"
    secondary = profile.secondary_color or "#ffffff"
    display = profile.display_font or "Inter"
    body = profile.body_font or "Inter"
    tagline = profile.tagline or ""
    tone_rules = profile.voice_dos or []
    donts = profile.voice_donts or []

    banned_words = list(_ABSOLUTE_BANS)
    for item in donts:
        if item and item.lower() not in (w.lower() for w in banned_words):
            banned_words.append(item)

    content_types_repr = repr({k: v for k, v in _CONTENT_TYPE_INSTRUCTIONS.items()})

    tone_rules_repr = repr([str(r) for r in tone_rules])
    banned_words_repr = repr([str(w) for w in banned_words])

    code = _SKILL_CODE_TEMPLATE.substitute(
        brand_name_repr=repr(brand_name),
        voice_repr=repr(voice),
        primary_repr=repr(primary),
        secondary_repr=repr(secondary),
        display_repr=repr(display),
        body_repr=repr(body),
        tagline_repr=repr(tagline),
        tone_rules_repr=tone_rules_repr,
        content_types_repr=content_types_repr,
        banned_words_repr=banned_words_repr,
        brand_name=brand_name,
    )

    return code


def forge_skill(profile: BrandProfile, output_dir: str = "./output/skills/") -> str:
    code = _render_code(profile)
    expanded = os.path.expanduser(output_dir)
    os.makedirs(expanded, exist_ok=True)
    slug = _to_slug(profile.name)
    filename = f"brand_{slug}_content.py"
    path = os.path.join(expanded, filename)
    with open(path, "w") as f:
        f.write(code)
    return path


def forge_skill_preview(profile: BrandProfile) -> str:
    return _render_code(profile)
